import { CodegenConfig } from "@graphql-codegen/cli";

const config: CodegenConfig = {
  schema: ["src/graphql/schema/**/*.ts", "src/segments/**/graphql.ts"],
  documents: ["src/{app,components,segments}/**/*.{ts,tsx}"],
  ignoreNoDocuments: true,
  generates: {
    "src/graphql/client/": {
      preset: "client",
      plugins: [],
      presetConfig: {
        fragmentMasking: { unmaskFunctionName: "getFragmentData" },
      },
      config: {
        scalars: {
          JSON: "@/types/json#Json",
          JSONObject: "@/types/json#JsonObject",
          Date: "string",
          DateTime: "string",
        },
      },
    },
    "src/types/graphql-schema.d.ts": {
      plugins: ["typescript", "typescript-resolvers"],
      config: {
        useIndexSignature: true,
        mapperTypeSuffix: "Model",
        mappers: {
          Brand: "@prisma/client#Brand",
          // CommunityMember: "@prisma/client#CommunityMember",
          // Viewer: "@prisma/client#User",
        },
        scalars: {
          JSON: "~/types/json#Json",
          JSONObject: "~/types/json#JsonObject",
          Date: {
            input: "Date | string",
            output: "Date",
          },
          DateTime: {
            input: "Date | string",
            output: "Date",
          },
        },
      },
    },
    "src/graphql/schema.graphql": {
      plugins: [
        {
          add: {
            content: [
              "# noinspection GraphQLTypeRedefinition",
              "# This file is generated by graphql-codegen. Do not edit it directly.",
            ],
          },
        },
        "schema-ast",
      ],
    },
  },
};

export default config;
